version: '3.1'
services:
    apache-php:
        build:
            context: apache-php
            dockerfile: Dockerfile
            args:
                STACK_ID: $STACK_ID
        image: o-apache-php:v0.1
        ports:
          - "${STACK_PORT}:8080"
        secrets:
          - dbuser
          - dbpass
        networks:
          - dmz
          - data
    mysql:
        build:
            context: mysql
            dockerfile: Dockerfile
            args:
                STACK_ID: $STACK_ID
        image: o-mysql:v0.1
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/rpass
            MYSQL_DATABASE: db
            MYSQL_USER_FILE: /run/secrets/dbuser
            MYSQL_PASSWORD_FILE: /run/secrets/dbpass
        secrets:
          - rpass
          - dbuser
          - dbpass
        volumes:
          - ${STACK_DIR}/${STACK_ID}/mysql:/var/lib/mysql
        networks:
          - data
secrets:
    rpass:
        file: ${STACK_DIR}/${STACK_ID}/secrets/rpass
    dbuser:
        file: ${STACK_DIR}/${STACK_ID}/secrets/dbuser
    dbpass:
        file: ${STACK_DIR}/${STACK_ID}/secrets/dbpass
networks:
    dmz:
    data:
        internal: true
